export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ERROR = 'SET_ERROR';
export const SET_NEXT_FIELD = 'SET_NEXT_FIELD';
export const SET_PREV_FIELD = 'SET_PREV_FIELD';
export const SET_PATIENT_DATA = 'SET_PATIENT_DATA';
export const SET_PATIENT_MEDICATION = 'SET_PATIENT_MEDICATION';
